[platformio]
default_envs = esp32-c3-devkitm-1

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I include
lib_deps = 
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit LTR390 Library @ ^1.1.2
    adafruit/Adafruit BusIO @ ^1.17.4

[env:esp32-c3-devkitm-1]
build_src_filter = 
    +<*>
    -<main_ltr390.cpp>

[env:esp32-c3-ltr390]
build_src_filter = 
    +<*>
    -<main.cpp>